<?php
$rowFormats = [
    // PROT_DATA
    'y' => [
        [
            'attr' => 'IndVeta',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^(y)$/g',
            'required' => true,
        ],
        [
            'attr' => 'Soubor',
            'type' => 'ARRAY',
            'length' => 14,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Dat_typ',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([ADFGH])$/g',
            'required' => true,
        ],
        [
            'attr' => 'Typ',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([NO])$/g',
            'required' => true,
        ],
        [
            'attr' => 'Dv',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Mv',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Rv',
            'type' => 'INT',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Do',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Mo',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Ro',
            'type' => 'INT',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Dd',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
        ],
        [
            'attr' => 'Md',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Rd',
            'type' => 'INT',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
    ],
    // PORAD_TV
    'a' => [
        [
            'attr' => 'IndVeta',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^(a)$/g',
            'required' => true,
        ],
        [
            'attr' => 'ST',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Dv',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Mv',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Rv',
            'type' => 'INT',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Ch',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Cm',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Cs',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'Sm_C',
            'type' => 'INT',
            'length' => 3,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'Ss_C',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'NAZEV',
            'type' => 'ARRAY',
            'length' => 50,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'SLEVA',
            'type' => 'INT',
            'length' => 3,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
    ],
    // SNIMEK_TV
    'b' => [
        [
            'attr' => 'IndVeta',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^(b)$/g',
            'required' => true,
        ],
        [
            'attr' => 'ID',
            'type' => 'ARRAY',
            'length' => 24,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'Sm_N',
            'type' => 'INT',
            'length' => 3,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'Ss_N',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'Sm_O',
            'type' => 'INT',
            'length' => 3,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => true,
        ],
        [
            'attr' => 'Ss_O',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'PREM',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([PR])$/g',
            'required' => false,
        ],
        [
            'attr' => 'ROK_VYR',
            'type' => 'INT',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'TITUL',
            'type' => 'ARRAY',
            'length' => 50,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => true,
        ],
        [
            'attr' => 'PODTITUL',
            'type' => 'ARRAY',
            'length' => 50,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'PUVOD',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([A-OYS])$/g',
            'required' => false,
        ],
        [
            'attr' => 'DISTRIB',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'VYROBCE',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'ZEME_VYR',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'OS',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'DRUHPOR',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([A-G])$/g',
            'required' => false,
        ],
        [
            'attr' => 'UPRAVA',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([A-O])$/g',
            'required' => false,
        ],
        [
            'attr' => 'PROGTYP',
            'type' => 'ARRAY',
            'length' => 3,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'TYPOLOGIE',
            'type' => 'ARRAY',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'NAVAZNOST',
            'type' => 'ARRAY',
            'length' => 2,
            'regex' => '/^(10|20|31|32|33|40|50)$/g',
            'required' => false,
        ],
        [
            'attr' => 'POCCASTI',
            'type' => 'INT',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'POZNAMKA',
            'type' => 'ARRAY',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
    ],
    // PODIL_TV
    'l' => [
        [
            'attr' => 'IndVeta',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^(l)$/g',
            'required' => true,
        ],
        [
            'attr' => 'TYP',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([AI])$/g',
            'required' => true,
        ],
        [
            'attr' => 'JMENO',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => true,
        ],
        [
            'attr' => 'RODCIS',
            'type' => 'INT',
            'length' => 10,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'BTTO',
            'type' => 'REAL',
            'length' => 10,
            'regex' => '/^([\-0-9][0-9]{6}\.[0-9]{2})$/g',
            'required' => false,
        ],
        [
            'attr' => 'VYKON',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'ULICE',
            'type' => 'ARRAY',
            'length' => 30,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'MISTO',
            'type' => 'ARRAY',
            'length' => 24,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'PSC',
            'type' => 'ARRAY',
            'length' => 10,
            'regex' => ServiceParser::DATA_TYPE_ARRAY_EXP,
            'required' => false,
        ],
        [
            'attr' => 'MOD',
            'type' =>'CHAR',
            'length' => 1,
            'regex' => '/^([ABC])$/g',
            'required' => true,
        ],
        [
            'attr' => 'Ds',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'Ms',
            'type' => 'INT',
            'length' => 2,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
        [
            'attr' => 'Rs',
            'type' => 'INT',
            'length' => 4,
            'regex' => ServiceParser::DATA_TYPE_INT_EXP,
            'required' => false,
        ],
    ],
];